name: Deploy Swift Package to Cloudflare Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: read
      deployments: write
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      # with:
      #   swift-version: '5.10.1'

    - name: Build Swift package
      run: swift build --configuration release

    - name: Run Swift package
      run: .build/release/JCalderitaWebSite

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
        directory: ./Build/
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        branch: main